"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.cartRoute = void 0;
var express_1 = require("express");
var cart_controller_1 = require("../controller/cart.controller");
exports.cartRoute = (0, express_1.Router)();
exports.cartRoute.post('/createCart', cart_controller_1.default.createCart);
exports.cartRoute.get('/getCart', cart_controller_1.default.getCartItems);
exports.cartRoute.delete('/clearCart', cart_controller_1.default.clearCart);
exports.cartRoute.put('/clearCart', cart_controller_1.default.updateCartItem);
