enum AuthRole {
  OPEN = 'OPEN',
  PROCUREMENT_MANAGER = 'PROCUREMENT_MANAGER',
  PROCUREMENT_ADMIN = 'PROCUREMENT_ADMIN',
  SITE_MANAGER = 'SITE_MANAGER',
  SUPERVISOR = 'SUPERVISOR',
  SUPPLIER = 'SUPPLIER',
}

export default AuthRole;
